export const H3_FRAMES_PER_SECOND = 24
export const H3_CONTINUATION_GUIDE_FRAMES = 22
export const H3_MAX_SEGMENT_DURATION_SECONDS = 11
export const H3_CONTINUATION_GUIDE_SECONDS = (
  H3_CONTINUATION_GUIDE_FRAMES / H3_FRAMES_PER_SECOND
)
export const H3_CONTINUATION_MIN_SOURCE_DURATION_MS = Math.ceil(
  H3_CONTINUATION_GUIDE_SECONDS * 1_000,
)
