export const AI_PROMPT_IDS = {
  CHARACTER_ANALYZE: 'character-analyze',
  CHARACTER_VISUAL_PROFILE: 'character-visual-profile',
  CHARACTER_CREATE: 'character-create',
  CHARACTER_MODIFY: 'character-modify',
  CHARACTER_UPDATE_DESCRIPTION: 'character-update-description',
  CHARACTER_REFERENCE_DESCRIBE_IMAGE: 'character-reference-describe-image',
  CHARACTER_REFERENCE_TO_SHEET: 'character-reference-to-sheet',
  LOCATION_ANALYZE: 'location-analyze',
  LOCATION_CREATE: 'location-create',
  LOCATION_MODIFY: 'location-modify',
  LOCATION_SPATIAL_PROFILE: 'location-spatial-profile',
  LOCATION_UPDATE_DESCRIPTION: 'location-update-description',
  PROP_ANALYZE: 'prop-analyze',
  PROP_UPDATE_DESCRIPTION: 'prop-update-description',
  SCRIPT_CLIP_SEGMENTS: 'script-clip-segments',
  SCRIPT_EPISODE_SPLIT: 'script-episode-split',
  SCRIPT_GENERATE_SCREENPLAY: 'script-generate-screenplay',
  SCRIPT_EXPAND_STORY: 'script-expand-story',
  STORYBOARD_PLAN: 'storyboard-plan',
  STORYBOARD_REFINE_CINEMATOGRAPHY: 'storyboard-refine-cinematography',
  STORYBOARD_REFINE_ACTING: 'storyboard-refine-acting',
  STORYBOARD_REFINE_DETAIL: 'storyboard-refine-detail',
  STORYBOARD_INSERT_PANEL: 'storyboard-insert-panel',
  SHOT_VARIANT_ANALYZE: 'shot-variant-analyze',
  SHOT_VARIANT_GENERATE: 'shot-variant-generate',
  PANEL_IMAGE_GENERATE: 'panel-image-generate',
  IMAGE_UPDATE_SHOT_PROMPT: 'image-update-shot-prompt',
  DESIGN_VISUAL_STYLE_PRESET: 'design-visual-style-preset',
  VOICE_GENERATE_LINES: 'voice-generate-lines',
  MUSIC_FINAL_RENDER_BGM: 'music-final-render-bgm',
  EDIT_SCRIPT_STYLE_BIBLE: 'edit-script-style-bible',
  EDIT_SCRIPT_SCREENPLAY: 'edit-script-screenplay',
  EDIT_SCRIPT_PRIMARY: 'edit-script-primary',
  EDIT_SCRIPT_ASSET_EXTRACT: 'edit-script-asset-extract',
  EDIT_SCRIPT_VIDEO_PROMPT_BLOCK: 'edit-script-video-prompt-block',
  EDIT_SCRIPT_VIDEO_BLOCK_ARRANGEMENT: 'edit-script-video-block-arrangement',
  EDIT_SCRIPT_VIDEO_BLOCK_MERGE: 'edit-script-video-block-merge',
  EDIT_SCRIPT_STORYBOARD_PANEL: 'edit-script-storyboard-panel',
  EDIT_SCRIPT_STORYBOARD_GRID_FLOOR_PLAN: 'edit-script-storyboard-grid-floor-plan',
  EDIT_SCRIPT_STORYBOARD_GRID_VISION: 'edit-script-storyboard-grid-vision',
  EDIT_SCRIPT_STORYBOARD_CAMERA_PLAN: 'edit-script-storyboard-camera-plan',
  EDIT_SCRIPT_STORYBOARD_CAMERA_STYLE_BIBLE: 'edit-script-storyboard-camera-style-bible',
  EDIT_SCRIPT_STORYBOARD_CAMERA_PLAN_BLOCK: 'edit-script-storyboard-camera-plan-block',
} as const

export type AiPromptId = (typeof AI_PROMPT_IDS)[keyof typeof AI_PROMPT_IDS]
