import { CODEX_API_CONFIG_CATALOG_MODELS, CODEX_BUILTIN_CAPABILITY_CATALOG_ENTRIES } from '@/lib/ai-providers/codex/models'
import { COMFYUI_API_CONFIG_CATALOG_MODELS, COMFYUI_BUILTIN_CAPABILITY_CATALOG_ENTRIES } from '@/lib/ai-providers/comfyui/models'

export const BUILTIN_CAPABILITY_CATALOG_ENTRIES = [
  ...CODEX_BUILTIN_CAPABILITY_CATALOG_ENTRIES,
  ...COMFYUI_BUILTIN_CAPABILITY_CATALOG_ENTRIES,
] as const

export const BUILTIN_API_CONFIG_CATALOG_MODELS = [
  ...CODEX_API_CONFIG_CATALOG_MODELS,
  ...COMFYUI_API_CONFIG_CATALOG_MODELS,
] as const
