import { ARK_API_CONFIG_CATALOG_MODELS, ARK_BUILTIN_CAPABILITY_CATALOG_ENTRIES, ARK_BUILTIN_PRICING_CATALOG_ENTRIES } from '@/lib/ai-providers/ark/models'
import { FAL_API_CONFIG_CATALOG_MODELS, FAL_BUILTIN_CAPABILITY_CATALOG_ENTRIES, FAL_BUILTIN_PRICING_CATALOG_ENTRIES } from '@/lib/ai-providers/fal/models'
import { GOOGLE_API_CONFIG_CATALOG_MODELS, GOOGLE_BUILTIN_CAPABILITY_CATALOG_ENTRIES, GOOGLE_BUILTIN_PRICING_CATALOG_ENTRIES } from '@/lib/ai-providers/google/models'
import { MUREKA_API_CONFIG_CATALOG_MODELS, MUREKA_BUILTIN_CAPABILITY_CATALOG_ENTRIES, MUREKA_BUILTIN_PRICING_CATALOG_ENTRIES } from '@/lib/ai-providers/mureka/models'
import { OPENAI_BUILTIN_PRICING_CATALOG_ENTRIES } from '@/lib/ai-providers/openai/models'
import { OPENROUTER_API_CONFIG_CATALOG_MODELS, OPENROUTER_BUILTIN_CAPABILITY_CATALOG_ENTRIES, OPENROUTER_BUILTIN_PRICING_CATALOG_ENTRIES } from '@/lib/ai-providers/openrouter/models'
import { TOONFLOW_API_CONFIG_CATALOG_MODELS, TOONFLOW_BUILTIN_CAPABILITY_CATALOG_ENTRIES, TOONFLOW_BUILTIN_PRICING_CATALOG_ENTRIES } from '@/lib/ai-providers/toonflow/models'

export const BUILTIN_CAPABILITY_CATALOG_ENTRIES = [
  ...ARK_BUILTIN_CAPABILITY_CATALOG_ENTRIES,
  ...FAL_BUILTIN_CAPABILITY_CATALOG_ENTRIES,
  ...GOOGLE_BUILTIN_CAPABILITY_CATALOG_ENTRIES,
  ...MUREKA_BUILTIN_CAPABILITY_CATALOG_ENTRIES,
  ...OPENROUTER_BUILTIN_CAPABILITY_CATALOG_ENTRIES,
  ...TOONFLOW_BUILTIN_CAPABILITY_CATALOG_ENTRIES,
] as const

export const BUILTIN_PRICING_CATALOG_ENTRIES = [
  ...ARK_BUILTIN_PRICING_CATALOG_ENTRIES,
  ...FAL_BUILTIN_PRICING_CATALOG_ENTRIES,
  ...GOOGLE_BUILTIN_PRICING_CATALOG_ENTRIES,
  ...MUREKA_BUILTIN_PRICING_CATALOG_ENTRIES,
  ...OPENAI_BUILTIN_PRICING_CATALOG_ENTRIES,
  ...OPENROUTER_BUILTIN_PRICING_CATALOG_ENTRIES,
  ...TOONFLOW_BUILTIN_PRICING_CATALOG_ENTRIES,
] as const

export const BUILTIN_API_CONFIG_CATALOG_MODELS = [
  ...ARK_API_CONFIG_CATALOG_MODELS,
  ...FAL_API_CONFIG_CATALOG_MODELS,
  ...GOOGLE_API_CONFIG_CATALOG_MODELS,
  ...MUREKA_API_CONFIG_CATALOG_MODELS,
  ...OPENROUTER_API_CONFIG_CATALOG_MODELS,
  ...TOONFLOW_API_CONFIG_CATALOG_MODELS,
] as const
