import { SCORE_PROHIBITIONS, type AudioDesign } from '@/lib/audio-design/types'

export function createValidAudioDesign(): AudioDesign {
  return {
    clock: { fps: 24, sampleRate: 48_000, totalFrames: 240 },
    soundWorlds: [{
      worldId: 'world-1',
      continuityKey: 'room-night-air',
      range: { startFrame: 0, endFrameExclusive: 240 },
      location: 'interior room',
      timeContext: 'night',
      weatherContext: null,
      persistentSourceIds: ['room-air'],
      perspectives: [{
        perspectiveId: 'perspective-1',
        zoneId: 'room-zone',
        range: { startFrame: 0, endFrameExclusive: 240 },
        enclosure: 'enclosed',
        distance: 'medium',
        occlusion: 0.1,
        description: 'stable enclosed perspective',
      }],
    }],
    acousticTransitions: [],
    soundPresence: [
      {
        segmentId: 'presence-1',
        range: { startFrame: 0, endFrameExclusive: 120 },
        mode: 'ambience_and_score',
        fadeInFrames: 12,
        fadeOutFrames: 12,
        reason: 'generated layers support the opening',
      },
      {
        segmentId: 'presence-2',
        range: { startFrame: 120, endFrameExclusive: 180 },
        mode: 'native_only',
        fadeInFrames: 8,
        fadeOutFrames: 8,
        reason: 'preserve native dialogue without generated layers',
      },
      {
        segmentId: 'presence-3',
        range: { startFrame: 180, endFrameExclusive: 240 },
        mode: 'ambience_and_score',
        fadeInFrames: 8,
        fadeOutFrames: 8,
        reason: 'generated layers return after dialogue',
      },
    ],
    ambienceSources: [{
      sourceId: 'ambience-1',
      sourceContinuityId: 'room-air',
      worldId: 'world-1',
      role: 'bed',
      playbackType: 'seamless_loop',
      semanticRole: 'neutral room tone',
      baseGainDb: -14,
      salience: 0.15,
      spectralRole: 'broadband',
      foregroundPolicy: 'background_only',
      range: { startFrame: 0, endFrameExclusive: 240 },
      generationPrompt: 'Steady neutral interior room tone with soft ventilation and no people.',
      promptInfluence: 0.7,
      candidateCount: 2,
      loopDurationSeconds: 10,
      crossfadeFrames: 12,
      phaseOffsetFrames: 0,
    }],
    scoreCues: [{
      cueId: 'score-1',
      musicalContinuityId: 'score-episode',
      range: { startFrame: 0, endFrameExclusive: 240 },
      narrativeDiagnosis: {
        surfaceEmotion: 'calm',
        trueScoringEmotion: 'contained pressure',
        scoringStance: 'minimal_presence',
        avoidEmotions: ['sentimentality'],
        musicShouldDo: 'maintain restrained pressure',
        musicShouldNotDo: 'literalize synchronized action',
      },
      musicTheorySpec: {
        bpm: 60,
        meter: '4/4',
        form: 'through_composed',
        metricSalience: 'suppressed',
        eventSpacing: 'asynchronous',
        pitch: {
          centerType: 'weakened_pitch_field',
          centerPitch: 'D',
          collection: 'evolving_pitch_class_sets',
          intervalRelations: ['minor_second_aggregation'],
          microtonality: 'limited',
        },
        harmony: {
          functionalSyntax: 'prohibited',
          cadencePolicy: 'no_cadence',
          harmonicRhythm: 'extremely_slow',
        },
        voiceLeading: ['incremental_micro_motion'],
        texture: {
          organization: 'independent_sustained_layers',
          density: 'sparse',
          layerIndependence: 0.8,
        },
        spectrum: {
          foundation: ['low'],
          upperActivity: 'isolated_partials',
          evolution: 'continuous_redistribution',
        },
        orchestration: [{
          instrument: 'filtered_analog_synthesizer',
          register: 'low',
          role: 'foundation',
          techniques: ['sustained_tone'],
        }],
        dynamics: {
          envelope: 'long_arc',
          transientPolicy: 'suppressed',
          minimumEnergy: 0.1,
          maximumEnergy: 0.4,
        },
        phases: [{
          phaseId: 'phase-1',
          range: { startFrame: 0, endFrameExclusive: 240 },
          function: 'establish',
          energy: 0.2,
          density: 'sparse',
          spectralBand: 'low',
          transientDensity: 0.05,
        }],
        prohibitions: [...SCORE_PROHIBITIONS],
      },
      intentionalSilenceRanges: [],
    }],
    automationLanes: [],
  }
}
