import { ARTIFACT_TYPES, type ArtifactType } from './types'

const invalidationMap: Record<ArtifactType, ArtifactType[]> = {
  [ARTIFACT_TYPES.STORY_RAW]: [
    ARTIFACT_TYPES.CREATIVE_BRIEF,
    ARTIFACT_TYPES.SUSPENSE_MECHANISM,
    ARTIFACT_TYPES.SHORT_SCRIPT,
    ARTIFACT_TYPES.SHOT_PLAN,
    ARTIFACT_TYPES.AUDIO_PLAN,
    ARTIFACT_TYPES.ANALYSIS_CHARACTERS,
    ARTIFACT_TYPES.ANALYSIS_LOCATIONS,
    ARTIFACT_TYPES.ANALYSIS_PROPS,
    ARTIFACT_TYPES.STORYBOARD_PANEL_SET,
  ],
  [ARTIFACT_TYPES.CREATIVE_BRIEF]: [
    ARTIFACT_TYPES.SUSPENSE_MECHANISM,
    ARTIFACT_TYPES.SHORT_SCRIPT,
    ARTIFACT_TYPES.SHOT_PLAN,
    ARTIFACT_TYPES.STORYBOARD_PANEL_SET,
    ARTIFACT_TYPES.AUDIO_PLAN,
    ARTIFACT_TYPES.PANEL_PROMPT,
    ARTIFACT_TYPES.PANEL_IMAGE,
    ARTIFACT_TYPES.PANEL_VIDEO,
  ],
  [ARTIFACT_TYPES.SUSPENSE_MECHANISM]: [
    ARTIFACT_TYPES.SHORT_SCRIPT,
    ARTIFACT_TYPES.SHOT_PLAN,
    ARTIFACT_TYPES.STORYBOARD_PANEL_SET,
    ARTIFACT_TYPES.AUDIO_PLAN,
    ARTIFACT_TYPES.PANEL_PROMPT,
    ARTIFACT_TYPES.PANEL_IMAGE,
    ARTIFACT_TYPES.PANEL_VIDEO,
  ],
  [ARTIFACT_TYPES.SHORT_SCRIPT]: [
    ARTIFACT_TYPES.SHOT_PLAN,
    ARTIFACT_TYPES.STORYBOARD_PANEL_SET,
    ARTIFACT_TYPES.AUDIO_PLAN,
    ARTIFACT_TYPES.PANEL_PROMPT,
    ARTIFACT_TYPES.PANEL_IMAGE,
    ARTIFACT_TYPES.PANEL_VIDEO,
  ],
  [ARTIFACT_TYPES.SHOT_PLAN]: [
    ARTIFACT_TYPES.STORYBOARD_PANEL_SET,
    ARTIFACT_TYPES.AUDIO_PLAN,
    ARTIFACT_TYPES.PANEL_PROMPT,
    ARTIFACT_TYPES.PANEL_IMAGE,
    ARTIFACT_TYPES.PANEL_VIDEO,
  ],
  [ARTIFACT_TYPES.AUDIO_PLAN]: [],
  [ARTIFACT_TYPES.ANALYSIS_CHARACTERS]: [
    ARTIFACT_TYPES.STORYBOARD_PANEL_SET,
  ],
  [ARTIFACT_TYPES.ANALYSIS_LOCATIONS]: [
    ARTIFACT_TYPES.STORYBOARD_PANEL_SET,
  ],
  [ARTIFACT_TYPES.ANALYSIS_PROPS]: [
    ARTIFACT_TYPES.STORYBOARD_PANEL_SET,
  ],
  [ARTIFACT_TYPES.STORYBOARD_PANEL_SET]: [
    ARTIFACT_TYPES.PANEL_PROMPT,
    ARTIFACT_TYPES.PANEL_IMAGE,
    ARTIFACT_TYPES.PANEL_VIDEO,
  ],
  [ARTIFACT_TYPES.PANEL_PROMPT]: [ARTIFACT_TYPES.PANEL_IMAGE, ARTIFACT_TYPES.PANEL_VIDEO],
  [ARTIFACT_TYPES.PANEL_IMAGE]: [ARTIFACT_TYPES.PANEL_VIDEO],
  [ARTIFACT_TYPES.PANEL_VIDEO]: [],
}

export function resolveInvalidatedArtifacts(type: ArtifactType): ArtifactType[] {
  return invalidationMap[type] || []
}
