import { TASK_TYPE, type TaskType } from './types'

export const TASK_RETRY_BACKOFF_BASE_MS = 15_000

const DEFAULT_TASK_MAX_ATTEMPTS = 1

const TASK_MAX_ATTEMPTS_OVERRIDES: Partial<Record<TaskType, number>> = {
  [TASK_TYPE.EDIT_STYLE_PREVIEWS_GENERATE]: 2,
  [TASK_TYPE.EDIT_SCRIPT_STORYBOARD_CAMERA_PLAN]: 2,
  [TASK_TYPE.EDIT_SCRIPT_GENERATE]: 2,
  [TASK_TYPE.EDIT_SHOT_EXECUTION_PLAN_GENERATE]: 2,
  [TASK_TYPE.FINAL_VIDEO_RENDER]: 1,
}

export function getTaskMaxAttempts(type: TaskType): number {
  return TASK_MAX_ATTEMPTS_OVERRIDES[type] ?? DEFAULT_TASK_MAX_ATTEMPTS
}
